expectedInputs:
- StartProcess: counts
  StartRange: 2

- StartProcess: compute
  StartRange: 3


workers:
  counts:
    Calculator:
      Target: 3600
      SpotTarget: 1200
      Run: 200
      Spinup: 160
    ScalerSim:
      PowerNeededMin: [500,2500]
      ChildWorker: Finish
      NumberOfChildren:  1
      BasePricePerHour: 0.0744
      SpotTimesCheaper: 4
      FastTimesMoreExpensive: 1.3
  compute:
    Calculator:
      Target: 3600
      SpotTarget: 1200
      Run: 500
      Spinup: 160
    ScalerSim:
      PowerNeededMin: [10,10000]
      ChildWorker: Finish
      NumberOfChildren:  1
      BasePricePerHour: 0.1144
      SpotTimesCheaper: 4
      FastTimesMoreExpensive: 1.3
