apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoscale-bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: workers
  name: autoscale-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments","deployments/scale"]
  verbs: ["get", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: autoscale-bot-binding
  namespace: workers
subjects:
- kind: ServiceAccount
  name: autoscale-bot
  namespace: default
roleRef:
  kind: Role
  name: autoscale-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscale-daemon-deployment
  labels:
    app: autoscale-daemon
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: autoscale-daemon
  template:
    metadata:
      labels:
        app: autoscale-daemon
    spec:
      serviceAccountName: autoscale-bot
      containers:
      - name: autoscale-daemon
        image: jot85/redis-work-queue-k8s-autoscale:0.3.4
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: "/etc/k8s-wqautoscale"
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: autoscale-config
